# Random Forest

In [ ]:
import pandas as pd
import numpy as np
from taxipred.utils.constants import DATA_PATH
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

df = pd.read_csv(DATA_PATH / "taxi_cleaned.csv")

df.sample(5)

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  \
548              9.15              2.0       2.12         0.84   
82               8.10              1.0       2.62         0.98   
285             42.26              3.0       2.30         1.69   
473             33.51              4.0       3.94         1.09   
125              2.19              1.0       2.80         0.51   

     Per_Minute_Rate  Trip_Duration_Minutes  Trip_Price  Time_of_Day_Evening  \
548             0.48                  81.26     48.8108                False   
82              0.13                  31.19     14.6127                False   
285             0.26                  40.14     84.1558                False   
473             0.32                  67.27     61.9923                False   
125             0.18                  14.20      6.4729                False   

     Time_of_Day_Morning  Time_of_Day_Night  Day_of_Week_Weekend  \
548                False              False                False   
82                 False              False                 True   
285                 True              False                False   
473                False              False                 True   
125                False              False                False   

     Traffic_Conditions_Low  Traffic_Conditions_Medium  Weather_Rain  \
548                   False                       True         False   
82                    False                      False         False   
285                   False                      False          True   
473                    True                      False          True   
125                   False                       True         False   

     Weather_Snow  
548          True  
82          False  
285         False  
473         False  
125         False

### 0. Divide into X and y

In [36]:
df_train = df.dropna(subset=["Trip_Price"])

X, y = df_train.drop("Trip_Price", axis="columns"), df_train["Trip_Price"]

X.head()

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  Per_Minute_Rate  \
0             19.35              3.0       3.56         0.80             0.32   
1             36.87              1.0       2.70         1.21             0.15   
2              8.64              2.0       2.55         1.71             0.48   
4             41.79              3.0       4.60         1.77             0.11   
5              9.91              2.0       2.32         1.26             0.34   

   Trip_Duration_Minutes  Time_of_Day_Evening  Time_of_Day_Morning  \
0                  53.82                False                 True   
1                  37.27                 True                False   
2                  89.33                False                False   
4                  86.95                False                False   
5                  41.72                 True                False   

   Time_of_Day_Night  Day_of_Week_Weekend  Traffic_Conditions_Low  \
0              False                False                    True   
1              False                 True                   False   
2              False                 True                   False   
4               True                 True                   False   
5              False                False                   False   

   Traffic_Conditions_Medium  Weather_Rain  Weather_Snow  
0                      False         False         False  
1                      False         False         False  
2                       True         False         False  
4                      False         False         False  
5                      False         False         False

In [37]:
y.info()

<class 'pandas.core.series.Series'>
Index: 548 entries, 0 to 573
Series name: Trip_Price
Non-Null Count  Dtype  
--------------  -----  
548 non-null    float64
dtypes: float64(1)
memory usage: 8.6 KB


### 1. train|test split

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42
    )


### 3. Training

In [39]:
rf = RandomForestRegressor()
rf.fit(X_train, y_train)

RandomForestRegressor()

### 4. Predict on test data

In [40]:
y_pred = rf.predict(X_test)
y_pred

array([ 47.202351,  34.139083, 103.03247 ,  26.62837 ,  41.495085,
        53.143618,  48.102824,  35.50659 ,  32.640743,  38.861049,
       105.728912,  48.547095,  30.895562,  30.468866,  45.364257,
        82.718273,  41.528045,  68.456045,  19.613508,  53.043204,
        60.347729,  54.664626,  24.599896,  58.844019,  32.289799,
        58.457153,  53.289006,  36.430604,  41.034965,  27.173739,
        29.119725,  57.199121,  22.691233,  95.428922,  83.333012,
        64.684062,  58.973167,  37.674024,  51.679329,  13.206982,
        92.268443,  71.15697 ,  13.29784 ,  64.047224,  70.200845,
        79.460514,  34.044331,  69.636247,  39.953261,  25.382662,
        51.855142,  17.5822  ,  72.468555,  77.235554,  89.135557,
        29.669058,  10.938207,  49.167432,  42.010258,  18.993482,
        55.594591,  16.494076,  44.577715,  71.691338,  78.52034 ,
        55.336738,  65.135698,  87.125293,  57.119597,  45.210681,
        15.517844,  36.468123,  69.082594,  52.870465,  48.575

### 5. Evaluation

In [41]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

mae, mse, rmse

(3.8389536850828696, 24.7887019673426, np.float64(4.978825360197182))

### RandomForestRegression gave us RMSE = 4.94

### Feature importance

In [42]:
rf.feature_importances_

array([0.49647645, 0.00526615, 0.01113029, 0.25523273, 0.07728778,
       0.14397845, 0.0015388 , 0.00136006, 0.00080637, 0.0014832 ,
       0.00164195, 0.00142513, 0.00153774, 0.0008349 ])

In [43]:
feature_importance = pd.DataFrame([X.columns, rf.feature_importances_]).T
feature_importance.columns = ["feature", "importance"]
feature_importance = feature_importance.sort_values(by="importance", ascending=False)
feature_importance

feature importance
0            Trip_Distance_km   0.496476
3                 Per_Km_Rate   0.255233
5       Trip_Duration_Minutes   0.143978
4             Per_Minute_Rate   0.077288
2                   Base_Fare    0.01113
1             Passenger_Count   0.005266
10     Traffic_Conditions_Low   0.001642
6         Time_of_Day_Evening   0.001539
12               Weather_Rain   0.001538
9         Day_of_Week_Weekend   0.001483
11  Traffic_Conditions_Medium   0.001425
7         Time_of_Day_Morning    0.00136
13               Weather_Snow   0.000835
8           Time_of_Day_Night   0.000806

### KNN

### 2. Scaling dataset

In [47]:
scaler = StandardScaler()
scaler.fit(X_train)

scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

scaled_X_train.min(), scaled_X_train.max(), scaled_X_test.min(), scaled_X_test.max()

(np.float64(-1.7360722288089256),
 np.float64(3.3516165253998453),
 np.float64(-1.716131388651957),
 np.float64(3.3516165253998453))

In [48]:
model = KNeighborsRegressor(n_neighbors=5)
model.fit(scaled_X_train, y_train)

KNeighborsRegressor()

In [50]:
y_pred_knn = model.predict(scaled_X_test)
y_pred_knn

array([34.68142, 37.35814, 86.93886, 31.39116, 44.0573 , 57.13154,
       52.73846, 43.43216, 45.66176, 56.47006, 85.08226, 72.60282,
       34.01706, 33.1681 , 33.20804, 49.86396, 53.40362, 74.05942,
       28.15162, 70.77734, 44.32356, 50.62904, 58.2023 , 61.1888 ,
       54.92822, 59.29056, 54.28084, 53.23018, 50.90856, 47.92202,
       33.28822, 49.93612, 29.28534, 68.02032, 63.53386, 52.98224,
       51.44574, 41.2538 , 37.83932, 23.72902, 70.2663 , 59.3227 ,
       21.56672, 50.86836, 51.7192 , 58.1848 , 43.26136, 43.0582 ,
       30.59618, 39.09782, 34.66232, 32.14676, 69.81758, 82.54776,
       70.93302, 37.62444, 19.85032, 54.28314, 66.94708, 34.98878,
       60.9143 , 33.60238, 46.95304, 71.27992, 75.7842 , 33.9704 ,
       70.03674, 66.82884, 47.41128, 50.92334, 20.9986 , 33.41082,
       80.05066, 49.94062, 50.70982, 69.57586, 62.4182 , 69.46356,
       54.21812, 44.44612, 44.25394, 57.44442, 40.32798, 65.29182,
       45.30976, 38.39766, 50.7717 , 47.4711 , 69.26724, 39.14

5. Evaluation

In [51]:
mae_knn = mean_absolute_error(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
rmse_knn = np.sqrt(mse)

mae_knn, mse_knn, rmse_knn

(11.0532964640884, 191.125459230221, np.float64(4.978825360197182))

### KNN gave us RMSE = 4.98